services:
  db:
    image: postgres:16
    restart: always
    container_name: litellm_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  litellm-tim:
    build: .
    ports:
      - "4001:4000"
    volumes:
      - ./config_tim.yaml:/app/config.yaml
      - ./litellm/proxy/hooks/tool_name_fixer_hook.py:/app/litellm/proxy/hooks/tool_name_fixer_hook.py
    env_file:
      - .tim.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: ["--config", "/app/config.yaml", "--port", "4000", "--detailed_debug"]
    depends_on:
      db:
        condition: service_healthy

  litellm-chrisann:
    build: .
    ports:
      - "4002:4000"
    volumes:
      - ./config_chrisann.yaml:/app/config.yaml
      - ./litellm/proxy/hooks/tool_name_fixer_hook.py:/app/litellm/proxy/hooks/tool_name_fixer_hook.py
    env_file:
      - .chrisann.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: ["--config", "/app/config.yaml", "--port", "4000", "--detailed_debug"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
