name: Validate model_prices_and_context_window.json

on:
  pull_request:
    branches:
      - main
      - litellm_internal_staging
      - litellm_oss_branch
      - "litellm_**"

permissions:
  contents: read

jobs:
  validate-model-prices-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Validate model_prices_and_context_window.json
        run: |
          jq empty model_prices_and_context_window.json
